spring:
  cloud:
    gateway:
      routes:
        - id: test_route_baidu
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_route_qq
          uri: http://www.qq.com
          predicates:
            - Query=url,qq
